ARG BASE_IMAGE
FROM $BASE_IMAGE AS base
ARG EXTRA_PACKAGES
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && \
    apt install -y \
    $EXTRA_PACKAGES \
    openssl \
    curl \
    iproute2 \
    iputils-ping \
    dnsutils \
    telnet \
    nginx \
    nginx-extras && \
    rm -rf /etc/nginx/conf.d && \
    mkdir /nginx && \
    ln -s /nginx /etc/nginx/conf.d && \
    sed -i 's/# server_tokens off;/server_tokens off;\n        more_clear_headers Server;/' /etc/nginx/nginx.conf && \
    echo '/usr/local/bin/check-mounting-path.sh --path="/nginx" --user="root" --chmod=755' >> /usr/local/bin/root-setup.sh && \
    echo 'if [ $? -ne 0 ]; then' >> /usr/local/bin/root-setup.sh && \
    echo '  exit -1' >> /usr/local/bin/root-setup.sh && \
    echo 'fi' >> /usr/local/bin/root-setup.sh && \
    echo '' >> /usr/local/bin/root-setup.sh && \
    echo 'service nginx start' >> /usr/local/bin/root-setup.sh && \
    echo '' >> /usr/local/bin/root-setup.sh && \
    rm -rf /tmp/*
ENTRYPOINT ["/usr/local/bin/main-run.sh"]
