ARG BASE_IMAGE
FROM $BASE_IMAGE AS base
ARG EXTRA_PACKAGES
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && \
    apt install -y \
    $EXTRA_PACKAGES \
    openssl \
    curl \
    wget \
    nginx \
    iproute2 \
    net-tools \
    iputils-ping \
    traceroute \
    dnsutils \
    telnet \
    netcat-openbsd \
    nmap && \
    rm -rf /tmp/*
ENTRYPOINT ["/usr/local/bin/main-run.sh"]
